#!/usr/bin/env python3
import os
import sys
import socket
import struct
import subprocess
import tempfile
import gitexternalblackw as gitblackw
import blackgit

type_map = {1: "commit", 2: "tree", 3: "blob", 4: "tag"}

def pdebug(line):
  sys.stderr.write(f"[R-DEBUG] {line}\n")
  sys.stderr.flush()

def perr(line):
  sys.stderr.write(line + "\n")
  sys.stderr.flush()

def getline():
  return sys.stdin.readline().strip()

class RemoteBlackW:
  def __init__(self):
    self.net = blackgit.Net()

  def run(self):
    try:
        self._run()
    except Exception as e:
      perr(f"Error: {e}")
      raise
    finally:
      self.net.close()

  def _run(self):
    while True:
      line = getline()
      if line == "":
        break
      pdebug(f"[git] {line}")
      if line == "capabilities":
        self.write("fetch\n")
        self.write("filter\n")
        self.write("push\n")
        self.write("list\n")
        self.write("option\n")
        self.write("\n")
      elif line.startswith("list"):
        self.get_list(line)
      elif line.startswith("fetch"):
        self.get_fetch(line)
      elif line.startswith("option"):
        self.do_option(line)
      else:
        perr(f"[git]unsupported operation: {line}")
        sys.exit(1)

  def do_option(self, line):
    if line.startswith("option verbosity"):
      self.write("ok\n")
    elif line.startswith("option filter"):
      self.write("ok\n")
    elif line.startswith("option from-promisor"):
      self.write("ok\n")
    elif line.startswith("option progress"):
      self.write("ok\n")
    elif line.startswith("option check-connectivity"):
      self.write("unsupported\n")
    else:
      self.write("unsupported\n")

  def get_list(self, line):
    resp = self.net.call('list')
    sha_name = resp.decode('utf-8')
    self.write(f"{sha_name}")
    self.write('\n')

  def _parse_fetch(self, line):
    ftargv = line.split(" ")
    if ftargv[1].startswith("--filter="):
      sha = ftargv[2]
      ref = ftargv[3]
    else:
      sha = ftargv[1]
      ref = ftargv[2]
    return (sha, ref)

  def get_fetch(self, line):
    while True:
      sha, ref = self._parse_fetch(line)
      pdebug(f"Fetching {sha} for {ref}")
      body = self._encode_fetch_request([sha])
      pack = self.net.call('fetch', body)
      self._write_pack(pack)

      pdebug(f"{line} end")
      line = getline()
      if line == "":
        break
    self.write("\n")
    pdebug("[git] fetch end")

  def _encode_fetch_request(self, shas):
    text = "\n".join(shas)
    return text.encode('utf-8')

  def _write_pack(self, pack):
    tmp = tempfile.NamedTemporaryFile(suffix='.pack', delete=False)
    try:
      tmp.write(pack)
      tmp.close()
      self.run_cmd(["git", "index-pack", "--stdin", "--promisor"], stdin=pack)
    finally:
      os.unlink(tmp.name)

  def run_cmd(self, cmd, *arg, stdin=None, **args):
    pdebug(f"run={cmd}")
    with subprocess.Popen(cmd,
                          stdout=subprocess.PIPE,
                          stderr=subprocess.PIPE,
                          stdin=subprocess.PIPE if stdin else None,
                          *arg, **args) as p:
      out, err = p.communicate(stdin)
      if out:
        pdebug(out.decode().strip())
      if err:
        pdebug(err.decode().strip())
      if p.returncode != 0:
        raise Exception(err.decode().strip())
      return out.decode().strip() if out else ""

  def write(self, message):
    sys.stdout.write(message)
    sys.stdout.flush()

def main():
  try:
    pdebug(f"argv={sys.argv}")
    if sys.argv[0].endswith("git-blackw"):
      blackw = gitblackw.ExternalBlackW()
      blackw.run(sys.argv)
    else:
      blackw = RemoteBlackW()
      blackw.run()
    return 0
  except Exception as e:
    perr(f"unexpected exception {e}")
    raise
  except KeyboardInterrupt:
    sys.exit(1)

if __name__ == "__main__":
  sys.exit(main())
