# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\x0c\x63om.blackgit\"&\n\tDListItem\x12\x0b\n\x03sha\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"?\n\x04List\x12\x0f\n\x07\x66orpush\x18\x01 \x01(\x08\x12&\n\x05items\x18\x02 \x03(\x0b\x32\x17.com.blackgit.DListItem\"\'\n\nDFetchItem\x12\x0b\n\x03sha\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\"=\n\x05\x46\x65tch\x12&\n\x04shas\x18\x01 \x03(\x0b\x32\x18.com.blackgit.DFetchItem\x12\x0c\n\x04pack\x18\x02 \x01(\x0c')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DLISTITEM']._serialized_start=31
  _globals['_DLISTITEM']._serialized_end=69
  _globals['_LIST']._serialized_start=71
  _globals['_LIST']._serialized_end=134
  _globals['_DFETCHITEM']._serialized_start=136
  _globals['_DFETCHITEM']._serialized_end=175
  _globals['_FETCH']._serialized_start=177
  _globals['_FETCH']._serialized_end=238
# @@protoc_insertion_point(module_scope)
